---
title: "Exploratory analysis script"
author: "Nicole Luisi"
date: "`r Sys.Date()`"
output: html_document
---

# Setup

```{r, echo=FALSE, message=FALSE}
# load R packages
library(here) 
library(ggplot2)
library(skimr) 
library(plotly)
library(gt)
library(knitr)
library(dplyr)
```

## Load data

```{r}
alldata<-readRDS(here("data", "processed_data", "allnewdx.rds"))
```

## Exploratory/Descriptive analysis

Full summary of the National data. 

```{r}
national<-alldata %>% filter(Geo %in% c("United States"))
national %>% gt::gt() %>% 
  gt::tab_header(title = "National Data") %>%
  gt::tab_style(style = list(gt::cell_fill(color = "#7cb9e8"),
                             gt::cell_text(weight = "bold")),
                locations = gt::cells_body(columns = Year))
```

Exploratory plots for the national rates by subgroup.

```{r}
national<-alldata %>% filter(Geo %in% c("United States"))
natfig <- plot_ly(national, x = ~Year, y = ~Overall_Rate, name = "Overall", type="scatter", mode = "lines", line = list(width = 3, dash = "dash", color = "gray")) 
natfig <- natfig %>% add_trace(y = ~Male_Rate, name = "Male", mode = 'lines', line = list(width = 3, dash = "solid", color = "blue"))
natfig <- natfig %>% add_trace(y = ~Female_Rate, name = "Female", mode = 'lines', line = list(width = 3, dash = "solid", color = "green"))
natfig %>% layout(title="National New Diagnosis Rate by Sex", legend=list(title=list(text='Sex')), 
                  xaxis = list(title = 'Year'),
                  yaxis = list(title = 'Rate per 100,000'))

natfig <- plot_ly(national, x = ~Year, y = ~Overall_Rate, name = "Overall", type="scatter", mode = "lines", line = list(width = 3, dash = "dash", color = "gray")) 
natfig <- natfig %>% add_trace(y = ~Black_Rate, name = "Black", mode = 'lines', line = list(width = 3, dash = "solid", color = "blue"))
natfig <- natfig %>% add_trace(y = ~White_Rate, name = "White", mode = 'lines', line = list(width = 3, dash = "solid", color = "darkgreen"))
natfig <- natfig %>% add_trace(y = ~Hispanic_Rate, name = "Hispanic", mode = 'lines', line = list(width = 3, dash = "solid", color = "darkred"))
natfig <- natfig %>% add_trace(y = ~Asian_Rate, name = "Asian", mode = 'lines', line = list(width = 3, dash = "solid", color = "cornflowerblue"))
natfig <- natfig %>% add_trace(y = ~AIAN_Rate, name = "AIAN", mode = 'lines', line = list(width = 3, dash = "solid", color = "brown1"))
natfig <- natfig %>% add_trace(y = ~MultRace_Rate, name = "Multiracial", mode = 'lines', line = list(width = 3, dash = "solid", color = "purple"))
natfig <- natfig %>% add_trace(y = ~NHPI_Rate, name = "NHPI", mode = 'lines', line = list(width = 3, dash = "solid", color = "magenta"))
natfig %>% layout(title="National New Diagnosis Rate by Race/Ethnicity", legend=list(title=list(text='Race/Ethnicity')), 
                  xaxis = list(title = 'Year'),
                  yaxis = list(title = 'Rate per 100,000'))

natfig <- plot_ly(national, x = ~Year, y = ~Overall_Rate, name = "Overall", type="scatter", mode = "lines", line = list(width = 3, dash = "dash", color = "gray")) 
natfig <- natfig %>% add_trace(y = ~Age13t24_Rate, name = "Age 13-24", mode = 'lines', line = list(width = 3, dash = "solid", color = "blue"))
natfig <- natfig %>% add_trace(y = ~Age25t34_Rate, name = "Age 25-34", mode = 'lines', line = list(width = 3, dash = "solid", color = "darkgreen"))
natfig <- natfig %>% add_trace(y = ~Age35t44_Rate, name = "Age 35-44e", mode = 'lines', line = list(width = 3, dash = "solid", color = "darkred"))
natfig <- natfig %>% add_trace(y = ~Age45t54_Rate, name = "Age 45-54", mode = 'lines', line = list(width = 3, dash = "solid", color = "cornflowerblue"))
natfig <- natfig %>% add_trace(y = ~Age55p_Rate, name = "Age 55+", mode = 'lines', line = list(width = 3, dash = "solid", color = "orange"))
natfig %>% layout(title="National New Diagnosis Rate by Age", legend=list(title=list(text='Age')), 
                  xaxis = list(title = 'Year'),
                  yaxis = list(title = 'Rate per 100,000'))
```

Summary of selected rate ratios for race/ethnicity and sex.

```{r}
national<-alldata %>% filter(Geo %in% c("United States"))
national_sub <- national %>% dplyr::select("Year", "Black_Rate", "White_Rate", "Hispanic_Rate", "black_white_rateratio", "hispanic_white_rateratio", "Male_Rate", "Female_Rate", "female_male_rateratio")
national_sub %>% gt::gt() %>% 
  gt::tab_header(title = "Rate Ratios") %>%
  gt::tab_style(style = list(gt::cell_fill(color = "#7cb9e8"),
                             gt::cell_text(weight = "bold")),
                locations = gt::cells_body(columns = Year))%>%
  gt::tab_style(style = list(gt::cell_fill(color = "#F1EB9C"),
                             gt::cell_text(weight = "bold")), 
                locations = gt::cells_body(columns = c(black_white_rateratio,hispanic_white_rateratio,female_male_rateratio)))
```

Full summary of the Regional data. 

```{r}
regional<-alldata %>% filter(Geo %in% c("Northeast", "Midwest", "South", "West"))
regional %>% gt::gt() %>% 
  gt::tab_header(title = "Regional Data") %>%
  gt::tab_style(style = list(gt::cell_fill(color = "#7cb9e8"),
                             gt::cell_text(weight = "bold")),
                locations = gt::cells_body(columns = Year))
```

Exploratory plot for regional overall new diagnosis rates with female-male rate ratios. 

```{r}
regional<-alldata %>% filter(Geo %in% c("Northeast", "Midwest", "South", "West"))
ggplot(regional, aes(x=Year, y=log(Overall_Rate), size=log(female_male_rateratio), color=Geo)) +
    geom_point(alpha=0.7) + scale_x_continuous(breaks=c(2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020)) +
  ggtitle("Regional New Diagnosis Rates with Female-Male Rate Ratios") +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab("Year") + ylab("Log of Overall NewDx Rate")
```


